import { Api} from "./atomAPI";
export const API: Api[]=[
    { id: 11, apiname: 'API1' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'上海',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-two',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '否',
    ServiceID: '12',
    ServiceName: 'api12',
    des:'消息控制',
    status:'已下线',
    time:'2018/4/16',
    ServicePort: '3000',
    APIType:'公共',
    ServiceTags: '原子'},
    { id: 12, apiname: 'API2' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'北京',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-two',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '否',
    ServiceID: '12',
    ServiceName: 'api12',
    des:'消息控制',
    status:'已发布',
    time:'2018/4/16',
    ServicePort: '3000',
    APIType:'公共',
    ServiceTags: '原子'},
    { id: 13, apiname: 'Bombasto' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'天津',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-three',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '是',
    ServiceID: '13',
    ServiceName: 'api13',
    des:'消息控制',
    status:'已下线',
    time:'2018/4/16',
    ServicePort: '8000',
    APIType:'私有',
    ServiceTags: '原子'},
    { id: 14, apiname: 'Celeritas' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-four',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '否',
    ServiceID: '14',
    ServiceName: 'api14',
    des:'消息控制',
    status:'已发布',
    time:'2018/4/16',
    ServicePort: '8080',
    APIType:'私有',
    ServiceTags: '原子'},
    { id: 15, apiname: 'Magneta' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-five',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '是',
    ServiceID: '15',
    ServiceName: 'API15',
    des:'消息控制',
    status:'已创建',
    time:'2018/4/16',
    ServicePort: '4200',
    APIType:'公共',
    ServiceTags: '原子'},
    { id: 16, apiname: 'RubberMan', Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-six',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '是',
    ServiceID: '16',
    ServiceName: 'api16',
    des:'消息控制',
    status:'已下线',
    time:'2018/4/16',
    ServicePort: '3000',
    APIType:'私有',
    ServiceTags: '原子' },
    { id: 17, apiname: 'Dynama' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-seven',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '否',
    ServiceID: '17',
    ServiceName: 'api17',
    des:'消息控制',
    status:'已下线',
    time:'2018/4/16',
    ServicePort: '4200',
    APIType:'公共',
    ServiceTags: '原子'},
    { id: 18, apiname: 'Dr IQ' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-eight',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '是',
    ServiceID: '18',
    ServiceName: 'api18',
    des:'消息控制',
    status:'已下线',
    time:'2018/4/16',
    ServicePort: '4200',
    APIType:'公共',
    ServiceTags: '原子'},
    { id: 19, apiname: 'Magma' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-nine',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '是',
    ServiceID: '19',
    ServiceName: 'api19',
    des:'消息控制',
    status:'已下线',
    time:'2018/4/16',
    ServicePort: '4200',
    APIType:'公共',
    ServiceTags: '原子'},
    { id: 20, apiname: 'Tornado' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-ten',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '否',
    ServiceID: '20',
    ServiceName: 'api20',
    des:'消息控制',
    status:'已下线',
    time:'2018/4/16',
    ServicePort: '4200',
    APIType:'公共',
    ServiceTags: '原子'},
    { id: 21, apiname: 'Tornado' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    Node: 'agent-ten',
    area:'',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '否',
    ServiceID: '20',
    ServiceName: 'api20',
    des:'消息控制',
    status:'已下线',
    time:'2018/4/16',
    ServicePort: '4200',
    APIType:'公共',
    ServiceTags: '原子'},
    { id: 22, apiname: 'Tornado' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-ten',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '否',
    ServiceID: '20',
    ServiceName: 'api20',
    des:'消息控制',
    status:'已下线',
    time:'2018/4/16',
    ServicePort: '4200',
    APIType:'公共',
    ServiceTags: '原子'},
    { id: 23, apiname: 'Tornado' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-ten',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '否',
    ServiceID: '20',
    ServiceName: 'api20',
    des:'消息控制',
    status:'已下线',
    time:'2018/4/16',
    ServicePort: '4200',
    APIType:'公共',
    ServiceTags: '原子'},
    { id: 24, apiname: 'Tornado' , Address:  "10.108.208.51",
    DataCenter:'dc1',
    area:'',
    method:'',
    path:'',
    successResult:'',
    errorResult:'',
    Node: 'agent-ten',
    ServiceAddress: 'localhost',
    ServiceEnableTagOverride: '否',
    ServiceID: '20',
    ServiceName: 'api20',
    des:'消息控制',
    status:'已下线',
    time:'2018/4/16',
    ServicePort: '4200',
    APIType:'公共',
    ServiceTags: '原子'}
]